name             'github-enterprise'
maintainer       'Rakuten, Inc.'
maintainer_email 'ops@rakops.com'
license          'Apache 2.0'
description      'Configures utilities for Github Enterprise'
long_description 'Configures utilities for Github Enterprise'
version          '2.0.0'

supports         'redhat'
supports         'centos'
supports         'fedora'
supports         'debian'
supports         'ubuntu'

depends          'git'
depends          'cron'
