name             'github-enterprise'
maintainer       'Rakuten, Inc.'
maintainer_email 'ops@rakops.com'
license          'Apache 2.0'
description      'Configures utilities for Github Enterprise'
long_description 'Configures utilities for Github Enterprise'
version          '0.1.0'

depends          'git'
depends          'cron'
